package com.example.demo.model;

public class Seat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.venue_id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    private String venueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.price_id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    private String priceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.postion_x
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    private String postionX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.position_y
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    private String positionY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.code
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.state
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seat.number
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.id
     *
     * @return the value of seat.id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.id
     *
     * @param id the value for seat.id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.venue_id
     *
     * @return the value of seat.venue_id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public String getVenueId() {
        return venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.venue_id
     *
     * @param venueId the value for seat.venue_id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public void setVenueId(String venueId) {
        this.venueId = venueId == null ? null : venueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.price_id
     *
     * @return the value of seat.price_id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public String getPriceId() {
        return priceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.price_id
     *
     * @param priceId the value for seat.price_id
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public void setPriceId(String priceId) {
        this.priceId = priceId == null ? null : priceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.postion_x
     *
     * @return the value of seat.postion_x
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public String getPostionX() {
        return postionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.postion_x
     *
     * @param postionX the value for seat.postion_x
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public void setPostionX(String postionX) {
        this.postionX = postionX == null ? null : postionX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.position_y
     *
     * @return the value of seat.position_y
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public String getPositionY() {
        return positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.position_y
     *
     * @param positionY the value for seat.position_y
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public void setPositionY(String positionY) {
        this.positionY = positionY == null ? null : positionY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.code
     *
     * @return the value of seat.code
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.code
     *
     * @param code the value for seat.code
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.state
     *
     * @return the value of seat.state
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.state
     *
     * @param state the value for seat.state
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seat.number
     *
     * @return the value of seat.number
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seat.number
     *
     * @param number the value for seat.number
     *
     * @mbg.generated Thu Sep 10 15:10:35 CST 2020
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }
}